apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice-ingress
  namespace: microservice-ingress-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /song/api/v1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: song-microservice-with-statefulset-service
                port:
                  number: 8081
          - path: /resource/api/v1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: resource-microservice-with-statefulset-service
                port:
                  number: 8080