apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice-ingress
  namespace: microservice-ingress-ns
#  annotations:
#    nginx.ingress.kubernetes.io/use-regex: "true"
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
#          - path: /api/v1/songs(/|$)(.*)
#            pathType: ImplementationSpecific
#            pathType: ImplementationSpecific
          - path: /
            pathType: Prefix
            backend:
              service:
                name: song-microservice-with-statefulset-service
                port:
                  number: 8081
#          - path: /api/v1/resources(/|$)(.*)
#            pathType: ImplementationSpecific
#            backend:
#              service:
#                name: resource-microservice-with-statefulset-service
#                port:
#                  number: 8080